server:
  port: 9002

spring:
  application:
    name: cloud-nacos-payment-service
  datasource:
    # 当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    # mysql驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.77.132:33306/atguigu_cloud2020?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
  # ================== Nacos 单节点情况下的配置信息
  #  cloud:
  #    nacos:
  #      discovery:
  #        server-addr: localhost:8848
  # ==================  不再是单点Nacos，而是通过nginx代理的Nacos集群，并且集成了mysql持久化功能；
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.77.132:80 # 通过nginx反向代理 nacos集群 并集成mysql做持久化服务；
      config:
        #        server-addr: localhost:8848 # nacos作为配置中心的地址
        server-addr: 192.168.77.132:80 # 通过nginx反向代理 nacos集群 并集成mysql做持久化服务；
        file-extension: yaml # 指定 yml格式的配置
    sentinel:
      transport:
        # Sentinel dashboard 地址
        dashboard: localhost:8080
        # sentinel会启动一个http server与dashboard进行通信，这个http server要占用8719端口
        # 假如 http server 默认占用的8719端口被占用后，应用会自动从8719开始依次 +1 扫描，直到找到没被占用的端口号；
        port: 8719

mybatis:
  #  它一般对应我们的实体类所在的包，这个时候会自动取对应包中不包括包名的简单类名作为包括包名的别名。多个package之间可以用逗号或者分号等来进行分隔（value的值一定要是包的全）
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.eiletxie.springcloud.entities

management:
  endpoints:
    web:
      exposure:
        include: "*"


